### ISSUE TITLE
Missing function: GetParent() 

### ISSUE THREAD

**Issue by hoppfrosch** [HotKeyIt/TT#3]
Within TT.ahk you make a call to the function GetParent()

This function is missing - Where does this function come from?

Using latest AutoHotkey_L (1.1.25.01 - Unicode - 32bit)

**Comment by hoppfrosch** [comment]
Already found it:
on line 469 of file TT.ahk it should read
`WinGetClass, sClass,% "ahk_id " DllCall("GetParent", "uint", hWndToolBar)`
instead of 
`WinGetClass, sClass,% "ahk_id " GetParent(hWndToolBar)`

**Comment by HotKeyIt** [comment]
This is because in AHK_H the function is included, I have fixed now
