### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by cycle4passion** [HotKeyIt/TT#5]
AHK_L Version 1.1.24.04
Included sizeof, _Struct, additional struct function
Is this written for AHK_H? multiple commands not quite right for AHK_L. By the time I fix them, ultimately it doesn't run.

Lines #82, 230:     
LoopParse,%options%,%A_Space%,%A_Space%
#364, 373, 669, 
WinGetControls, controls,% "ahk_id " hWndTray:=WinExist("ahk_class Shell_TrayWnd")
WinGetPid, procpid, ahk_id %hWndToolBar%

**Comment by HotKeyIt** [comment]
Looks like you picked up v2 version, try using v1 version: https://github.com/HotKeyIt/TT/blob/master/TT.ahk

**Comment by cycle4passion** [comment]
thank you
